#!/bin/bash

set -ex

VERSION=dev
if [[ "$SOURCE_BRANCH" =~ ^v[0-9]+.[0-9]+.[0-9]+$ ]]; then
  VERSION=${SOURCE_BRANCH:1}
fi

docker build \
  --build-arg VERSION=$VERSION \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  -e "ATTEMPTS=${ATTEMPTS:-3}" \
  -e "TIMEOUT=${TIMEOUT:-1}" \
  -e "SUCCESS_TIMEOUT=${SUCCESS_TIMEOUT:-1}" \
  -e "SUCCESS_ATTEMPTS=${SUCCESS_ATTEMPTS:-1}" \
  -e "CURL_RETRY=${CURL_RETRY:-}" \
  -e "CURL_OPTIONS=${CURL_OPTIONS:-}" \
  -e "CURL_CONNECTION_TIMEOUT=${CURL_CONNECTION_TIMEOUT:-}" \
  -e "CURL_RETRY=${CURL_RETRY:-}" \
  -e "CURL_RETRY_DELAY${CURL_RETRY_DELAY:-}" \
  -e "CURL_RETRY_MAX_TIME=${CURL_RETRY_MAX_TIME:-}" \
  -f $DOCKERFILE_PATH \
  -t $IMAGE_NAME .